#ifndef ESNATIVE_VERSION_H_INCLUDED
#define ESNATIVE_VERSION_H_INCLUDED

#define ESNATIVE_VERSION_MAJOR "0"
#define ESNATIVE_VERSION_MINOR "0"
#define ESNATIVE_VERSION_PATCH "1"
// #define ESNATIVE_VERSION_TWEAK ""

#endif // ESNATIVE_VERSION_H_INCLUDE
